Port all Junit assert to Truth asserts
google/gson pull request #2304
Opened 2023-01-28 14:10 UTC by MaicolAntali

All test inside the path `gson/gson/src/test` are ported to Truth

2023-01-29 19:06 UTC, Marcono1234 reviewed
Thanks! Might be useful to adjust the tests to use Truth more effectively, for example in some cases there are assertions such as `assertThat(... == ...).isTrue()` (though these manual comparisons also existed before your changes).

I have started commenting on some of the cases below, but stopped after I noticed that commenting on every case is probably not worth it and useful.

Though I don't know how important Éamonn considers these adjustments. So feel free to ignore my suggestion.

2023-01-30 14:34 UTC, MaicolAntali commented
> I have started commenting on some of the cases below, but stopped after I noticed that commenting on every case is probably not worth it and useful.

To port this amount of tests to the Truth I had to use Regex (where was possible) because do it manually would have taken too long. There are a tons of things that can be changed or/and optimized but I don't know if it's worth.

My main idea was: Port the tests without change things that are not related to `assert` because I knew that this PR was pretty huge and I wanted to keep the things much easier as possible. We could optimize tests in a next PR so it will be more easy to review

Anyway, thanks for the review and comments! 😄

2023-01-31 16:22 UTC, eamonnmcmanus requested changes
We can tweak these assertions more or less indefinitely. I think it is fine if you don't. Perhaps just do the ones that @Marcono1234 commented on. This is still an improvement, and we may be able to use Error Prone to pick up further simplifications.

2023-01-31 16:22 UTC, eamonnmcmanus commented on gson/src/test/java/com/google/gson/functional/ArrayTest.java
>      for (int i = 0; i < expected.length; ++i) {
Yes, especially since the existing code will succeed even if `actual.length > expected.length`. (This is already true before the change, of course.)

2023-01-31 16:22 UTC, eamonnmcmanus commented on gson/src/test/java/com/google/gson/functional/ArrayTest.java
> +    assertThat(array[0]).isNull();
I think this would work:
```
assertThat(array).asList().containsExactly(null);
```

2023-01-31 16:22 UTC, eamonnmcmanus commented on gson/src/test/java/com/google/gson/functional/ArrayTest.java
> +    assertThat(target[0]).isEqualTo("Hello");
```
assertThat(target).asList().containsExactly("Hello", "World");
```

2023-01-31 16:22 UTC, eamonnmcmanus commented on gson/src/test/java/com/google/gson/functional/ArrayTest.java
> +    assertThat(arrayType.length).isEqualTo(1);
Yes. Also no need to assert the length if you use `.containsExactly`.

2023-01-31 16:42 UTC, MaicolAntali commented
> we may be able to use Error Prone to pick up further simplifications.

I already looked how to setting up the `maven-compiler-plugin` to implement Error Prone. Probably my next PR will be related to this.

2023-01-31 19:20 UTC, eamonnmcmanus approved these changes

2023-01-31 19:20 UTC, eamonnmcmanus commented
OK, I think this is a good step on the way. Thanks again!

2023-01-31 19:20 UTC, merged

2023-02-04 01:41 UTC, Marcono1234 reviewed
Thanks for addressing my comments!

Sorry for this late follow-up review; I think in two cases the array comparison should use `inOrder()`. Though this might not be so important.

2023-02-04 01:41 UTC, Marcono1234 commented on gson/src/test/java/com/google/gson/functional/ArrayTest.java
> +    assertThat(target).asList().containsAnyIn(expected);
Should probably be `containsExactly(...).inOrder()` as well.
```suggestion
    assertThat(target).asList().containsExactly(expected).inOrder();
```

2023-02-04 01:41 UTC, Marcono1234 commented on gson/src/test/java/com/google/gson/functional/ArrayTest.java
> +    assertThat(target).asList().containsExactly("Hello", "World");
```suggestion
    assertThat(target).asList().containsExactly("Hello", "World").inOrder();
```