Only create one `BoundField` instance per field in `ReflectiveTypeAdapterFactory`
google/gson pull request #2440
Opened 2023-07-20 22:15 UTC by Marcono1234

### Purpose
Fixes #2438

### Description
Instead of creating a `BoundField` for every possible name of a field (for `@SerializedName` usage) and then storing for that `BoundField` whether it is serialized or deserialized, instead only create one `BoundField` and then have a separate `Map<String, BoundField>` for deserialized fields, and a separate `List<BoundField>` for serialized fields.

This shouldn't cause any changes visible to the user.

Not sure if this implementation is clean enough; feedback is appreciated!

### Checklist

- [x] New code follows the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)
- [ ] If necessary, new public API validates arguments, for example rejects `null`
- [ ] New public API has Javadoc
    - [ ] Javadoc uses `@since $next-version$`  
      (`$next-version$` is a special placeholder which is automatically replaced during release)
- [x] If necessary, new unit tests have been added  
  - [x] Assertions in unit tests use [Truth](https://truth.dev/), see existing tests
  - [x] No JUnit 3 features are used (such as extending class `TestCase`)
  - [ ] If this pull request fixes a bug, a new test was added for a situation which failed previously and is now fixed
- [x] `mvn clean verify javadoc:jar` passes without errors

2023-09-29 19:49 UTC, eamonnmcmanus requested changes
This looks great. I ran it past Google's tests and had no problems. (Except one place where people were accessing the internals of `ReflectiveTypeAdapterFactory` via reflection. I'll update that at the same time as I import these changes.)

Just one trivial request.

2023-09-29 19:49 UTC, eamonnmcmanus commented on gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java
> +    + " declares multiple JSON fields named '" + duplicateName + "'; conflict is caused"
Would you mind indenting these +4?

2023-09-30 19:54 UTC, Marcono1234 commented on gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java
> +    + " declares multiple JSON fields named '" + duplicateName + "'; conflict is caused"
Thanks for noticing!

2023-09-30 20:23 UTC, eamonnmcmanus approved these changes

2023-09-30 20:23 UTC, merged