Move enum and `JsonElement` adapter classes to separate class files
google/gson pull request #2727
Opened 2024-08-11 13:06 UTC by Marcono1234

### Purpose
Make internal code easier to read and maintain by moving classes to separate class files.

### Description
Their implementation is complex enough to probably justify having them in their own class files, to make maintaining them easier. For the users this should not be noticeable since these classes are still in the Gson internal package.

I have also added a few comments to the implementations.

### Checklist

- [x] New code follows the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)\
  This is automatically checked by `mvn verify`, but can also be checked on its own using `mvn spotless:check`.\
  Style violations can be fixed using `mvn spotless:apply`; this can be done in a separate commit to verify that it did not cause undesired changes.
- [ ] If necessary, new public API validates arguments, for example rejects `null`
- [ ] New public API has Javadoc
    - [ ] Javadoc uses `@since $next-version$`  
      (`$next-version$` is a special placeholder which is automatically replaced during release)
- [ ] If necessary, new unit tests have been added  
  - [ ] Assertions in unit tests use [Truth](https://truth.dev/), see existing tests
  - [ ] No JUnit 3 features are used (such as extending class `TestCase`)
  - [ ] If this pull request fixes a bug, a new test was added for a situation which failed previously and is now fixed
- [x] `mvn clean verify javadoc:jar` passes without errors

2024-08-11 16:22 UTC, eamonnmcmanus requested changes
I like this a lot. I'm certainly not a fan of giant anonymous classes! However, even though people shouldn't be accessing the `.internal.` APIs, you just know they do. [Here](https://github.com/immutables/immutables/blob/4c737f7fcc3e00799b12e57f3f6abd6b3ebcd800/mongo/test/org/immutables/mongo/bson4gson/Jsons.java#L33) is an example. It doesn't cost much to keep the public fields in `TypeAdapters` and just change how they get their values. So I think we should do that.

2024-08-13 20:37 UTC, Marcono1234 commented
Good point, I forgot to consider that. I added back `JSON_ELEMENT` and `ENUM_FACTORY`, but not `JSON_ELEMENT_FACTORY` because it [seems to be rarely used](https://github.com/search?q=%22JSON_ELEMENT_FACTORY%22+language%3AJava+NOT+path%3AGson.java+NOT+path%3ATypeAdapters.java&type=code). Is that ok?

2024-08-13 22:14 UTC, eamonnmcmanus commented
I think we might as well just keep all the public fields? It doesn't cost much.

2024-08-17 12:26 UTC, Marcono1234 commented
Ok, I have added `JSON_ELEMENT_FACTORY` back as well. I was a bit worried that we keep accumulating `@Deprecated` fields and methods in Gson's internal code this way, but so far it is not that bad yet.

2024-08-17 15:08 UTC, eamonnmcmanus approved these changes

2024-08-17 15:09 UTC, merged